name: Auto Update Thndr Dashboard
on:
  schedule:
    - cron: '0 15 * * *' # يحدث كل يوم الساعة 5 مساء بتوقيت مصر
  workflow_dispatch:     # تقدر تشغله يدويًا من GitHub Actions

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Update timestamp
        run: |
          echo "Last update: $(date)" > last_update.txt
      - name: Commit & Push
        run: |
          git config --global user.name "Thndr AutoBot"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Automatic daily update"
          git push
